ALTER TABLE `Interview` ADD COLUMN IF NOT EXISTS `status` VARCHAR(191) NOT NULL DEFAULT 'Scheduled';
ALTER TABLE `Interview` ADD COLUMN IF NOT EXISTS `round` VARCHAR(191) NULL;
ALTER TABLE `Interview` ADD COLUMN IF NOT EXISTS `type` VARCHAR(191) NULL DEFAULT 'Video Call';
ALTER TABLE `Interview` ADD COLUMN IF NOT EXISTS `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `Interview` ADD COLUMN IF NOT EXISTS `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
