ALTER TABLE `Department`
  ADD COLUMN `code` VARCHAR(191) NULL,
  ADD COLUMN `head` VARCHAR(191) NULL,
  ADD COLUMN `parent` VARCHAR(191) NULL DEFAULT 'Corporate',
  ADD COLUMN `description` TEXT NULL,
  ADD COLUMN `color` VARCHAR(191) NULL DEFAULT '#4f46e5',
  ADD COLUMN `status` VARCHAR(191) NULL DEFAULT 'Active';
